### ISSUE TITLE
(in)Consistency of pillar keys

### ISSUE THREAD

**Issue by johnkeates** [saltstack-formulas/haproxy-formula#29]
I'm thinking about refactoring some of the pillar keys since right now it's a mix of concatenated words, words with dashes and maybe even words with underscores. While it works fine, it's bad in terms of consistency. This means that in practise, a key might have an unexpected spelling and therefore not work at all if one format is presumed but a different non-standard format is used as a pillar key.

I'm suggesting using the same formatting as HAProxy does itself, this way the key consistency (or formatting consistency) is directly derived from HAProxy and thus should match presumptions made from  the config documentation. So crt-base will be crt-base in the config and the pillar as well. In the pillar, log-format is log format right now, that would be changed to log-format so the config and pillar match up again.

Another option would be to change all the pillar keys to the same formatting, but right now it's neither and it's inconsistent as a whole. Unless someone is completely against it, I'll change it and merge the updated keys and put in a warning that old config might not work if you use the old keys.

**Comment by gravyboat** [comment]
I'm all for consistency. My familiarity with this formula's formatting is a bit limited so let's see if anyone else weighs in prior to going ahead with this. If no one responds in a couple days I'd be happy to merge a PR for this.

**Comment by johnkeates** [comment]
I'm closing this in favour of #57
