### ISSUE TITLE
Hardcoded log path in global

### ISSUE THREAD

**Issue by jlory** [saltstack-formulas/haproxy-formula#46]
It seems that log in global is hard coded, is there a reason for that?

http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#log

**Comment by gravyboat** [comment]
@jlory Is the functionality you want not supported here: https://github.com/saltstack-formulas/haproxy-formula/blob/master/haproxy/templates/haproxy.jinja#L91 via https://github.com/saltstack-formulas/haproxy-formula/blob/master/pillar.example#L35? Or are you specifically trying to modify the values set in global here: https://github.com/saltstack-formulas/haproxy-formula/blob/master/haproxy/templates/haproxy.jinja#L25-L27? If the second one is the case it should be pretty trivial to add that option via the pillar and I would be happy to review it and merge that in as long as it includes the default existing setting so we don't break backwards compatibility.

**Comment by jlory** [comment]
It's the one is your second statement ( global ) indeed :) I can do a quick fix for that, I was curious why

    log /dev/log    local0
    log /dev/log    local1 notice

are the defaults values? Is it what you found on Debian?

**Comment by gravyboat** [comment]
I have no idea to be honest. I didn't write this formula so my familiarity with deploying it isn't that great.

**Comment by johnkeates** [comment]
I wrote that. It's the default that was in the HAProxy config I was using at the time.

**Comment by hoonetorg** [comment]
Wouldn't that be a solution?
https://github.com/hoonetorg/haproxy-formula/commit/59edb270b72078449b259bfd3de9eaec70563fa1

a pillar would look like this:
```
haproxy:
  global:
    log:
      - 127.0.0.1 local2
      - 127.0.0.1 local1 notice
```

**Comment by hoonetorg** [comment]
I could create a PR if you want.

**Comment by johnkeates** [comment]
Looks fine to me. PR that stuff! Someone will probably merge it.

**Comment by hoonetorg** [comment]
see https://github.com/saltstack-formulas/haproxy-formula/pull/50

**Comment by daks** [comment]
Hello,
the PR was merged, can this issue be closed?
