### ISSUE TITLE
make haproxy.cfg template more modular

### ISSUE THREAD

**Issue by hoonetorg** [saltstack-formulas/haproxy-formula#49]
please see my develop branch at https://github.com/hoonetorg/haproxy-formula for the changes to the haproxy.jinja.

I could create a pull request if you like,
but probably there is something to discuss before :).

**Comment by hoonetorg** [comment]
see https://github.com/saltstack-formulas/haproxy-formula/pull/51

**Comment by gravyboat** [comment]
Closing since #51 is merged.
