### ISSUE TITLE
running formula with pillar.example failed 

### ISSUE THREAD

**Issue by hvnsweeting** [saltstack-formulas/haproxy-formula#60]
Test on Ubuntu 14.04

Error

```
[ERROR   ] output:  * Starting haproxy haproxy
[ALERT] 267/055217 (17381) : config : no <listen> line. Nothing to do !
[ALERT] 267/055217 (17381) : Fatal errors found in configuration.
   ...fail!
```

Is that consider an error?

**Comment by daks** [comment]
pillar.example is just that an example, so it must be adapted to your needs.
I think this issue can be closed.

**Comment by daks** [comment]
Pillar.example has changed, and tests use it now. So closing this issue
